import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
